version: "3.8"

services:
  toko-app:
    container_name: toko-app
    build: ./docker/app
    depends_on:
      - toko-mongo
    volumes:
      - ./:/work
    ports:
      - 30080:8080
    networks:
      - app

  toko-mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 30017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb
    networks:
      - app

  toko-mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - toko-mongo
    ports:
      - 30081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: toko-mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - app

networks:
  app:
    driver: bridge